### ISSUE TITLE
IssueSubmit#2-mgwein: main branch on hipergator

### ISSUE THREAD

**Issue by mgwein** [weecology/DeepTreeAttention#148]
running with no errors, but no comet.ml chart or matrix outputs

[DeepTreeAttention_24071851.out.txt](https://github.com/weecology/DeepTreeAttention/files/8399994/DeepTreeAttention_24071851.out.txt)
[DeepTreeAttention_24071851.err.txt](https://github.com/weecology/DeepTreeAttention/files/8399995/DeepTreeAttention_24071851.err.txt)

**Comment by bw4sz** [comment]
Can you make the project public. The .txt says

```
https://www.comet.ml/mgwein/deeptreeattention/e002deec0c74447aa768fe24cb05d442
```

**Comment by bw4sz** [comment]
Clearly something is being logged, if you look at the .err you see a good looking comet summary. I'll need to see the comet page online. Any recent changes?

**Comment by mgwein** [comment]
> Clearly something is being logged, if you look at the .err you see a good looking comet summary. I'll need to see the comet page online. Any recent changes?

no changes, made public

**Comment by mgwein** [comment]
> running with no errors, but no comet.ml chart or matrix outputs
> 
> [DeepTreeAttention_24071851.out.txt](https://github.com/weecology/DeepTreeAttention/files/8399994/DeepTreeAttention_24071851.out.txt) [DeepTreeAttention_24071851.err.txt](https://github.com/weecology/DeepTreeAttention/files/8399995/DeepTreeAttention_24071851.err.txt)

Actually noticing the following error:

```
Traceback (most recent call last):
  File "/blue/azare/mgwein/DeepTreeAttention/DeepTreeAttention/train.py", line 85, in <module>
    m = main.TreeModel(
  File "/blue/azare/mgwein/DeepTreeAttention/DeepTreeAttention/src/main.py", line 62, in __init__
    if not loss_weight:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by bw4sz** [comment]
yeah, I just did that, fixing now. my mistake.

**Comment by bw4sz** [comment]
fixed.

**Comment by mgwein** [comment]
Running clean!!

Curious, is this just unnecessary computing on the HiPerGator (https://github.com/weecology/DeepTreeAttention/issues/145#issuecomment-1083358175)?
