### ISSUE TITLE
SMOTE augmentation?

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepTreeAttention#75]

**Comment by bw4sz** [comment]
@MarconiS does this work only on pixels? Linear combinations of images seems weird.

**Comment by MarconiS** [comment]
Sorry, I just saw this. I don't know how to do it at the individual level. Maybe the closest thing I can think of is data augmentation through synthetic data (GAN generated trees?), but in all fairness given the complexity of spectral + spatial information I would be very surprised if it would generate meaningful synthetic trees

**Comment by bw4sz** [comment]
Agreed. Closing hard to envision worth it. Maybe for the far off future.
